# Generated by Django 5.1.15 on 2026-08-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('GRAPH', 'Graph Algorithms'), ('SORTING', 'Sorting Algorithms'), ('TREES', 'Trees'), ('DP', 'Dynamic Programming'), ('OS', 'Operating System Scheduling'), ('DBMS', 'DBMS'), ('NETWORKING', 'Computer Networks'), ('COMPILER', 'Compiler Design'), ('ML', 'Machine Learning')], default='GRAPH', max_length=50)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('description', models.TextField()),
                ('pseudocode', models.TextField()),
                ('time_complexity', models.CharField(max_length=100)),
                ('space_complexity', models.CharField(max_length=100)),
                ('theory_content', models.JSONField(default=dict, help_text='Detailed theory sections (intro, applications, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
